version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env-docker
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

